-- Convert schema 'db/EngDatabase-Schema-0.22-SQLite.sql' to 'db/EngDatabase-Schema-0.23-SQLite.sql':;

BEGIN;

DROP INDEX affiliationgroup;

DROP INDEX both02;

DROP INDEX primarygroup;

CREATE UNIQUE INDEX affiliationgroup02 ON PP_GROUP_MEMBERSHIPS (GROUP_MEMBERSHIP_ID, AFFILIATION_GROUP);

CREATE UNIQUE INDEX both0202 ON PP_GROUP_MEMBERSHIPS (GROUP_MEMBERSHIP_ID, PRIMARY_GROUP, AFFILIATION_GROUP);

CREATE UNIQUE INDEX primarygroup02 ON PP_GROUP_MEMBERSHIPS (GROUP_MEMBERSHIP_ID, PRIMARY_GROUP);


COMMIT;

