-- Convert schema 'db/EngDatabase-Schema-0.19-SQLite.sql' to 'db/EngDatabase-Schema-0.20-SQLite.sql':;

BEGIN;

CREATE TEMPORARY TABLE PP_STATUSES_temp_alter (
  STATUS_ID INTEGER PRIMARY KEY NOT NULL,
  STATUS_NAME ,
  AD_PASSWORD ,
  AUTOMOUNTER ,
  AD_ENABLED ,
  TRUST_ALLOWED ,
  UNIX_PASSWD ,
  UNIX_ENABLED ,
  PROP_TEACH ,
  PROP_MAIL ,
  PROP_DIVA ,
  PROP_DIVB ,
  PROP_DIVF ,
  PROP_FLUID ,
  PROP_STRUCT ,
  PROP_WHITTLE ,
  PROP_WORKS ,
  PROP_TEST 
);

INSERT INTO PP_STATUSES_temp_alter( STATUS_ID, STATUS_NAME, AD_PASSWORD, AUTOMOUNTER, AD_ENABLED, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST) SELECT STATUS_ID, STATUS_NAME, AD_PASSWORD, AUTOMOUNTER, AD_ENABLED, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_STATUSES;

DROP TABLE PP_STATUSES;

CREATE TABLE PP_STATUSES (
  STATUS_ID INTEGER PRIMARY KEY NOT NULL,
  STATUS_NAME ,
  AD_PASSWORD ,
  AUTOMOUNTER ,
  AD_ENABLED ,
  TRUST_ALLOWED ,
  UNIX_PASSWD ,
  UNIX_ENABLED ,
  PROP_TEACH ,
  PROP_MAIL ,
  PROP_DIVA ,
  PROP_DIVB ,
  PROP_DIVF ,
  PROP_FLUID ,
  PROP_STRUCT ,
  PROP_WHITTLE ,
  PROP_WORKS ,
  PROP_TEST 
);

CREATE UNIQUE INDEX PP_STATUSES_STATUS_NAME03 ON PP_STATUSES (STATUS_NAME);

INSERT INTO PP_STATUSES SELECT STATUS_ID, STATUS_NAME, AD_PASSWORD, AUTOMOUNTER, AD_ENABLED, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_TEACH, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_STATUSES_temp_alter;

DROP TABLE PP_STATUSES_temp_alter;

DROP INDEX PP_USERS_CRSID;

DROP INDEX PP_USERS_ENGID;

DROP INDEX PP_USERS_UID;

CREATE TEMPORARY TABLE PP_USER_CAPABILITIES_temp_alter (
  CAPABILITIES_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer NOT NULL,
  AD_ENABLED integer,
  AD_PASSWORD integer,
  AUTOMOUNTER integer,
  TRUST_ALLOWED integer,
  UNIX_PASSWD integer,
  UNIX_ENABLED integer,
  PROP_TEACH integer,
  PROP_MAIL integer,
  PROP_DIVA integer,
  PROP_DIVB integer,
  PROP_DIVF integer,
  PROP_FLUID integer,
  PROP_STRUCT integer,
  PROP_WHITTLE integer,
  PROP_WORKS integer,
  PROP_TEST integer,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PP_USER_CAPABILITIES_temp_alter( CAPABILITIES_ID, USER_ID, AD_ENABLED, AD_PASSWORD, AUTOMOUNTER, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST) SELECT CAPABILITIES_ID, USER_ID, AD_ENABLED, AD_PASSWORD, AUTOMOUNTER, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_USER_CAPABILITIES;

DROP TABLE PP_USER_CAPABILITIES;

CREATE TABLE PP_USER_CAPABILITIES (
  CAPABILITIES_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer NOT NULL,
  AD_ENABLED integer,
  AD_PASSWORD integer,
  AUTOMOUNTER integer,
  TRUST_ALLOWED integer,
  UNIX_PASSWD integer,
  UNIX_ENABLED integer,
  PROP_TEACH integer,
  PROP_MAIL integer,
  PROP_DIVA integer,
  PROP_DIVB integer,
  PROP_DIVF integer,
  PROP_FLUID integer,
  PROP_STRUCT integer,
  PROP_WHITTLE integer,
  PROP_WORKS integer,
  PROP_TEST integer,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX PP_USER_CAPABILITIES_idx_US00 ON PP_USER_CAPABILITIES (USER_ID);

CREATE UNIQUE INDEX PP_USER_CAPABILITIES_CAPABI00 ON PP_USER_CAPABILITIES (CAPABILITIES_ID, USER_ID);

INSERT INTO PP_USER_CAPABILITIES SELECT CAPABILITIES_ID, USER_ID, AD_ENABLED, AD_PASSWORD, AUTOMOUNTER, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_TEACH, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_USER_CAPABILITIES_temp_alter;

DROP TABLE PP_USER_CAPABILITIES_temp_alter;


COMMIT;

