-- 
-- Created by SQL::Translator::Producer::MySQL
-- Created on Tue Nov  5 13:11:26 2013
-- 
SET foreign_key_checks=0;

DROP TABLE IF EXISTS `PP_ATTRIBUTES`;

--
-- Table: `PP_ATTRIBUTES`
--
CREATE TABLE `PP_ATTRIBUTES` (
  `ATTRIBUTE_ID` integer(11) NOT NULL,
  `ATTRIBUTE_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ATTRIBUTE_ID`),
  UNIQUE `name` (`ATTRIBUTE_NAME`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `PP_GROUPS`;

--
-- Table: `PP_GROUPS`
--
CREATE TABLE `PP_GROUPS` (
  `GROUP_ID` integer(11) NOT NULL,
  `GID` integer(11) NOT NULL,
  `GROUP_NAME` varchar(50) NULL,
  `GROUP_DESC` varchar(100) NULL,
  PRIMARY KEY (`GROUP_ID`),
  UNIQUE `GID` (`GID`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `PP_STATUSES`;

--
-- Table: `PP_STATUSES`
--
CREATE TABLE `PP_STATUSES` (
  `STATUS_ID` integer(11) NOT NULL,
  `STATUS_NAME` varchar(100) NULL,
  `AD_PASSWORD` integer(1) NULL,
  `AUTOMOUNTER` integer(1) NULL,
  `AD_ENABLED` integer(1) NULL,
  `TRUST_ALLOWED` integer(1) NULL,
  `UNIX_PASSWD` integer(1) NULL,
  `UNIX_ENABLED` integer(1) NULL,
  `PROP_TEACH` integer(1) NULL,
  `PROP_MAIL` integer(1) NULL,
  `PROP_DIVA` integer(1) NULL,
  `PROP_DIVB` integer(1) NULL,
  `PROP_DIVF` integer(1) NULL,
  `PROP_FLUID` integer(1) NULL,
  `PROP_STRUCT` integer(1) NULL,
  `PROP_WHITTLE` integer(1) NULL,
  `PROP_WORKS` integer(1) NULL,
  `PROP_TEST` integer(1) NULL,
  PRIMARY KEY (`STATUS_ID`),
  UNIQUE `PP_STATUSES_STATUS_NAME` (`STATUS_NAME`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `PP_USERS`;

--
-- Table: `PP_USERS`
--
CREATE TABLE `PP_USERS` (
  `USER_ID` integer(11) NOT NULL,
  `CRSID` varchar(10) NOT NULL,
  `ENGID` text NULL,
  `UID` integer(11) NOT NULL,
  `GECOS` varchar(100) NULL,
  `HOMEDIR` varchar(100) NULL,
  `PASSWORD_EXPIRY_DATE` varchar(100) NULL,
  `PROPAGATION` varchar(100) NULL,
  `STATUS_ID` integer(11) NOT NULL,
  `STATUS_DATE` date NULL,
  INDEX `PP_USERS_idx_STATUS_ID` (`STATUS_ID`),
  PRIMARY KEY (`USER_ID`),
  UNIQUE `CRSID` (`CRSID`),
  UNIQUE `ENGID` (`ENGID`),
  UNIQUE `both` (`ENGID`, `CRSID`),
  CONSTRAINT `PP_USERS_fk_STATUS_ID` FOREIGN KEY (`STATUS_ID`) REFERENCES `PP_STATUSES` (`STATUS_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `PP_USER_CAPABILITIES`;

--
-- Table: `PP_USER_CAPABILITIES`
--
CREATE TABLE `PP_USER_CAPABILITIES` (
  `CAPABILITIES_ID` integer(11) NOT NULL,
  `USER_ID` integer(11) NOT NULL,
  `AD_ENABLED` integer(1) NULL,
  `AD_PASSWORD` integer(1) NULL,
  `AUTOMOUNTER` integer(1) NULL,
  `TRUST_ALLOWED` integer(1) NULL,
  `UNIX_PASSWD` integer(1) NULL,
  `UNIX_ENABLED` integer(1) NULL,
  `PROP_TEACH` integer(1) NULL,
  `PROP_MAIL` integer(1) NULL,
  `PROP_DIVA` integer(1) NULL,
  `PROP_DIVB` integer(1) NULL,
  `PROP_DIVF` integer(1) NULL,
  `PROP_FLUID` integer(1) NULL,
  `PROP_STRUCT` integer(1) NULL,
  `PROP_WHITTLE` integer(1) NULL,
  `PROP_WORKS` integer(1) NULL,
  `PROP_TEST` integer(1) NULL,
  INDEX `PP_USER_CAPABILITIES_idx_USER_ID` (`USER_ID`),
  PRIMARY KEY (`CAPABILITIES_ID`),
  UNIQUE `PP_USER_CAPABILITIES_CAPABILITIES_ID_USER_ID` (`CAPABILITIES_ID`, `USER_ID`),
  CONSTRAINT `PP_USER_CAPABILITIES_fk_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `PP_USERS` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `PP_GROUP_MEMBERSHIPS`;

--
-- Table: `PP_GROUP_MEMBERSHIPS`
--
CREATE TABLE `PP_GROUP_MEMBERSHIPS` (
  `GROUP_MEMBERSHIP_ID` integer(11) NOT NULL,
  `USER_ID` integer(11) NOT NULL,
  `GROUP_ID` integer(11) NOT NULL,
  `PRIMARY_GROUP` integer(1) NOT NULL,
  `AFFILIATION_GROUP` integer(1) NOT NULL,
  INDEX `PP_GROUP_MEMBERSHIPS_idx_GROUP_ID` (`GROUP_ID`),
  INDEX `PP_GROUP_MEMBERSHIPS_idx_USER_ID` (`USER_ID`),
  PRIMARY KEY (`GROUP_MEMBERSHIP_ID`),
  UNIQUE `affiliationgroup` (`USER_ID`, `AFFILIATION_GROUP`),
  UNIQUE `both` (`USER_ID`, `PRIMARY_GROUP`, `AFFILIATION_GROUP`),
  UNIQUE `primarygroup` (`USER_ID`, `PRIMARY_GROUP`),
  CONSTRAINT `PP_GROUP_MEMBERSHIPS_fk_GROUP_ID` FOREIGN KEY (`GROUP_ID`) REFERENCES `PP_GROUPS` (`GROUP_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `PP_GROUP_MEMBERSHIPS_fk_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `PP_USERS` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `PP_USER_ATTRIBUTES`;

--
-- Table: `PP_USER_ATTRIBUTES`
--
CREATE TABLE `PP_USER_ATTRIBUTES` (
  `USER_ATTRIBUTE_ID` integer(11) NOT NULL,
  `USER_ID` integer(11) NOT NULL,
  `ATTRIBUTE_ID` integer(11) NOT NULL,
  `ATTRIBUTE_VALUE` varchar(100) NULL,
  `ATTRIBUTE_EFFECTIVE_DATE` date NULL,
  `ATTRIBUTE_EXPIRY_DATE` date NULL,
  INDEX `PP_USER_ATTRIBUTES_idx_ATTRIBUTE_ID` (`ATTRIBUTE_ID`),
  INDEX `PP_USER_ATTRIBUTES_idx_USER_ID` (`USER_ID`),
  PRIMARY KEY (`USER_ATTRIBUTE_ID`),
  UNIQUE `both` (`USER_ID`, `ATTRIBUTE_EFFECTIVE_DATE`, `ATTRIBUTE_EXPIRY_DATE`),
  UNIQUE `effective` (`USER_ID`, `ATTRIBUTE_EFFECTIVE_DATE`),
  UNIQUE `expiry` (`USER_ID`, `ATTRIBUTE_EXPIRY_DATE`),
  CONSTRAINT `PP_USER_ATTRIBUTES_fk_ATTRIBUTE_ID` FOREIGN KEY (`ATTRIBUTE_ID`) REFERENCES `PP_ATTRIBUTES` (`ATTRIBUTE_ID`),
  CONSTRAINT `PP_USER_ATTRIBUTES_fk_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `PP_USERS` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

SET foreign_key_checks=1;

