-- Convert schema 'db/EngDatabase-Schema-0.22-SQLite.sql' to 'db/EngDatabase-Schema-0.23-SQLite.sql':;

BEGIN;

CREATE TEMPORARY TABLE PP_GROUP_MEMBERSHIPS_temp_alter (
  GROUP_MEMBERSHIP_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  GROUP_ID integer(11) NOT NULL,
  PRIMARY_GROUP integer(1),
  AFFILIATION_GROUP integer(1),
  FOREIGN KEY (GROUP_ID) REFERENCES PP_GROUPS(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PP_GROUP_MEMBERSHIPS_temp_alter( GROUP_MEMBERSHIP_ID, USER_ID, GROUP_ID, PRIMARY_GROUP, AFFILIATION_GROUP) SELECT GROUP_MEMBERSHIP_ID, USER_ID, GROUP_ID, PRIMARY_GROUP, AFFILIATION_GROUP FROM PP_GROUP_MEMBERSHIPS;

DROP TABLE PP_GROUP_MEMBERSHIPS;

CREATE TABLE PP_GROUP_MEMBERSHIPS (
  GROUP_MEMBERSHIP_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  GROUP_ID integer(11) NOT NULL,
  PRIMARY_GROUP integer(1),
  AFFILIATION_GROUP integer(1),
  FOREIGN KEY (GROUP_ID) REFERENCES PP_GROUPS(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX PP_GROUP_MEMBERSHIPS_idx_GR00 ON PP_GROUP_MEMBERSHIPS (GROUP_ID);

CREATE INDEX PP_GROUP_MEMBERSHIPS_idx_US00 ON PP_GROUP_MEMBERSHIPS (USER_ID);

CREATE UNIQUE INDEX affiliationgroup03 ON PP_GROUP_MEMBERSHIPS (AFFILIATION_GROUP);

CREATE UNIQUE INDEX both0203 ON PP_GROUP_MEMBERSHIPS (PRIMARY_GROUP, AFFILIATION_GROUP);

CREATE UNIQUE INDEX primarygroup03 ON PP_GROUP_MEMBERSHIPS (PRIMARY_GROUP);

INSERT INTO PP_GROUP_MEMBERSHIPS SELECT GROUP_MEMBERSHIP_ID, USER_ID, GROUP_ID, PRIMARY_GROUP, AFFILIATION_GROUP FROM PP_GROUP_MEMBERSHIPS_temp_alter;

DROP TABLE PP_GROUP_MEMBERSHIPS_temp_alter;


COMMIT;

