-- 
-- Created by SQL::Translator::Producer::Oracle
-- Created on Fri Sep 13 13:27:02 2013
-- 
--
-- Table: PP_ATTRIBUTES
--;

DROP TABLE "PP_ATTRIBUTES" CASCADE CONSTRAINTS;

CREATE TABLE "PP_ATTRIBUTES" (
  "ATTRIBUTE_ID" number NOT NULL,
  "ATTRIBUTE_NAME" varchar2(4000) NOT NULL,
  PRIMARY KEY ("ATTRIBUTE_ID"),
  CONSTRAINT "PP_ATTRIBUTES_ATTRIBUTE_NAME" UNIQUE ("ATTRIBUTE_NAME")
)
ENGINE    InnoDB;

--
-- Table: PP_GROUPS
--;

DROP TABLE "PP_GROUPS" CASCADE CONSTRAINTS;

CREATE TABLE "PP_GROUPS" (
  "GROUP_ID" number NOT NULL,
  "GID" number NOT NULL,
  "GROUP_NAME" varchar2(4000) NOT NULL,
  "GROUP_DESC" varchar2(4000),
  PRIMARY KEY ("GROUP_ID"),
  CONSTRAINT "PP_GROUPS_GROUP_NAME_GID" UNIQUE ("GROUP_NAME", "GID")
)
ENGINE    InnoDB;

--
-- Table: PP_STATUSES
--;

DROP TABLE "PP_STATUSES" CASCADE CONSTRAINTS;

CREATE TABLE "PP_STATUSES" (
  "STATUS_ID" number NOT NULL,
  "STATUS_NAME" varchar2(4000),
  "AD_PASSWORD" varchar2(4000),
  "AUTOMOUNTER" varchar2(4000),
  "AD_ENABLED" varchar2(4000),
  "TRUST_ALLOWED" varchar2(4000),
  "UNIX_PASSWD" varchar2(4000),
  "UNIX_ENABLED" varchar2(4000),
  "PROP_DEPT" varchar2(4000),
  "PROP_MAIL" varchar2(4000),
  "PROP_DIVA" varchar2(4000),
  "PROP_DIVB" varchar2(4000),
  "PROP_DIVF" varchar2(4000),
  "PROP_FLUID" varchar2(4000),
  "PROP_STRUCT" varchar2(4000),
  "PROP_WHITTLE" varchar2(4000),
  "PROP_WORKS" varchar2(4000),
  "PROP_TEST" varchar2(4000),
  PRIMARY KEY ("STATUS_ID"),
  CONSTRAINT "PP_STATUSES_STATUS_NAME" UNIQUE ("STATUS_NAME")
)
ENGINE    InnoDB;

--
-- Table: PP_USERS
--;

DROP TABLE "PP_USERS" CASCADE CONSTRAINTS;

CREATE TABLE "PP_USERS" (
  "USER_ID" number NOT NULL,
  "CRSID" varchar2(4000) NOT NULL,
  "ENGID" varchar2(4000),
  "UID" number NOT NULL,
  "GECOS" varchar2(4000),
  "HOMEDIR" varchar2(4000),
  "PASSWORD_EXPIRY_DATE" varchar2(4000),
  "PROPAGATION" varchar2(4000),
  "STATUS_ID" number NOT NULL,
  "STATUS_DATE" varchar2(4000),
  PRIMARY KEY ("USER_ID"),
  CONSTRAINT "PP_USERS_ENGID_CRSID_UID" UNIQUE ("ENGID", "CRSID", "UID")
)
ENGINE    InnoDB;

--
-- Table: PP_USER_CAPABILITIES
--;

DROP TABLE "PP_USER_CAPABILITIES" CASCADE CONSTRAINTS;

CREATE TABLE "PP_USER_CAPABILITIES" (
  "CAPABILITIES_ID" number NOT NULL,
  "USER_ID" number NOT NULL,
  "STATUS_NAME" varchar2(4000),
  "AD_PASSWORD" varchar2(4000),
  "AUTOMOUNTER" varchar2(4000),
  "AD_ENABLED" varchar2(4000),
  "TRUST_ALLOWED" varchar2(4000),
  "UNIX_PASSWD" varchar2(4000),
  "UNIX_ENABLED" varchar2(4000),
  "PROP_DEPT" varchar2(4000),
  "PROP_MAIL" varchar2(4000),
  "PROP_DIVA" varchar2(4000),
  "PROP_DIVB" varchar2(4000),
  "PROP_DIVF" varchar2(4000),
  "PROP_FLUID" varchar2(4000),
  "PROP_STRUCT" varchar2(4000),
  "PROP_WHITTLE" varchar2(4000),
  "PROP_WORKS" varchar2(4000),
  "PROP_TEST" varchar2(4000),
  PRIMARY KEY ("CAPABILITIES_ID"),
  CONSTRAINT "PP_USER_CAPABILITIES_CAPABILITIES_ID_USER_ID" UNIQUE ("CAPABILITIES_ID", "USER_ID")
)
ENGINE    InnoDB;

--
-- Table: PP_GROUP_MEMBERSHIPS
--;

DROP TABLE "PP_GROUP_MEMBERSHIPS" CASCADE CONSTRAINTS;

CREATE TABLE "PP_GROUP_MEMBERSHIPS" (
  "GROUP_MEMBERSHIP_ID" number NOT NULL,
  "USER_ID" number NOT NULL,
  "GROUP_ID" number NOT NULL,
  PRIMARY KEY ("GROUP_MEMBERSHIP_ID")
)
ENGINE    InnoDB;

--
-- Table: PP_USER_ATTRIBUTES
--;

DROP TABLE "PP_USER_ATTRIBUTES" CASCADE CONSTRAINTS;

CREATE TABLE "PP_USER_ATTRIBUTES" (
  "USER_ATTRIBUTE_ID" number NOT NULL,
  "USER_ID" clob NOT NULL,
  "ATTRIBUTE_ID" number NOT NULL,
  "ATTRIBUTE_VALUE" varchar2(4000),
  "ATTRIBUTE_EFFECTIVE_DATE" varchar2(4000),
  "ATTRIBUTE_EXPIRY_DATE" varchar2(4000),
  PRIMARY KEY ("USER_ATTRIBUTE_ID")
)
ENGINE    InnoDB;

ALTER TABLE "PP_USERS" ADD CONSTRAINT "PP_USERS_STATUS_ID_fk" FOREIGN KEY ("STATUS_ID") REFERENCES "PP_STATUSES" ("STATUS_ID") ON DELETE CASCADE;

ALTER TABLE "PP_USER_CAPABILITIES" ADD CONSTRAINT "PP_USER_CAPABILITIES_USER_ID_f" FOREIGN KEY ("USER_ID") REFERENCES "PP_USERS" ("USER_ID");

ALTER TABLE "PP_GROUP_MEMBERSHIPS" ADD CONSTRAINT "PP_GROUP_MEMBERSHIPS_GROUP_ID_" FOREIGN KEY ("GROUP_ID") REFERENCES "PP_GROUPS" ("GROUP_ID") ON DELETE CASCADE;

ALTER TABLE "PP_GROUP_MEMBERSHIPS" ADD CONSTRAINT "PP_GROUP_MEMBERSHIPS_USER_ID_f" FOREIGN KEY ("USER_ID") REFERENCES "PP_USERS" ("USER_ID") ON DELETE CASCADE;

ALTER TABLE "PP_USER_ATTRIBUTES" ADD CONSTRAINT "PP_USER_ATTRIBUTES_ATTRIBUTE_I" FOREIGN KEY ("ATTRIBUTE_ID") REFERENCES "PP_ATTRIBUTES" ("ATTRIBUTE_ID");

ALTER TABLE "PP_USER_ATTRIBUTES" ADD CONSTRAINT "PP_USER_ATTRIBUTES_USER_ID_fk" FOREIGN KEY ("USER_ID") REFERENCES "PP_USERS" ("USER_ID") ON DELETE CASCADE;

CREATE INDEX "PP_USERS_idx_STATUS_ID" on "PP_USERS" ("STATUS_ID");

CREATE INDEX "PP_USER_CAPABILITIES_idx_USER_" on "PP_USER_CAPABILITIES" ("USER_ID");

CREATE INDEX "PP_GROUP_MEMBERSHIPS_idx_GROUP" on "PP_GROUP_MEMBERSHIPS" ("GROUP_ID");

CREATE INDEX "PP_GROUP_MEMBERSHIPS_idx_USER_" on "PP_GROUP_MEMBERSHIPS" ("USER_ID");

CREATE INDEX "PP_USER_ATTRIBUTES_idx_ATTRIBU" on "PP_USER_ATTRIBUTES" ("ATTRIBUTE_ID");

CREATE INDEX "PP_USER_ATTRIBUTES_idx_USER_ID" on "PP_USER_ATTRIBUTES" ("USER_ID");

/

