-- Convert schema 'db/EngDatabase-Schema-0.22-SQLite.sql' to 'db/EngDatabase-Schema-0.23-SQLite.sql':;

BEGIN;

CREATE TEMPORARY TABLE PP_GROUP_MEMBERSHIPS_temp_alter (
  GROUP_MEMBERSHIP_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  GROUP_ID integer(11) NOT NULL,
  FOREIGN KEY (GROUP_ID) REFERENCES PP_GROUPS(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PP_GROUP_MEMBERSHIPS_temp_alter( GROUP_MEMBERSHIP_ID, USER_ID, GROUP_ID) SELECT GROUP_MEMBERSHIP_ID, USER_ID, GROUP_ID FROM PP_GROUP_MEMBERSHIPS;

DROP TABLE PP_GROUP_MEMBERSHIPS;

CREATE TABLE PP_GROUP_MEMBERSHIPS (
  GROUP_MEMBERSHIP_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  GROUP_ID integer(11) NOT NULL,
  FOREIGN KEY (GROUP_ID) REFERENCES PP_GROUPS(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX PP_GROUP_MEMBERSHIPS_idx_GR00 ON PP_GROUP_MEMBERSHIPS (GROUP_ID);

CREATE INDEX PP_GROUP_MEMBERSHIPS_idx_US00 ON PP_GROUP_MEMBERSHIPS (USER_ID);

INSERT INTO PP_GROUP_MEMBERSHIPS SELECT GROUP_MEMBERSHIP_ID, USER_ID, GROUP_ID FROM PP_GROUP_MEMBERSHIPS_temp_alter;

DROP TABLE PP_GROUP_MEMBERSHIPS_temp_alter;

CREATE TEMPORARY TABLE PP_USERS_temp_alter (
  USER_ID INTEGER PRIMARY KEY NOT NULL,
  CRSID varchar2(10) NOT NULL,
  ENGID text,
  UID integer(11),
  GECOS varchar2(100),
  HOMEDIR varchar2(100),
  PASSWORD_EXPIRY_DATE varchar2(100),
  PROPAGATION varchar2(100),
  STATUS_ID integer(11),
  STATUS_DATE date,
  PRIMARY_GROUP integer(11),
  AFFILIATION_GROUP integer(11),
  FOREIGN KEY (PRIMARY_GROUP) REFERENCES PP_GROUPS(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (STATUS_ID) REFERENCES PP_STATUSES(STATUS_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PP_USERS_temp_alter( USER_ID, CRSID, ENGID, UID, GECOS, HOMEDIR, PASSWORD_EXPIRY_DATE, PROPAGATION, STATUS_ID, STATUS_DATE, PRIMARY_GROUP, AFFILIATION_GROUP) SELECT USER_ID, CRSID, ENGID, UID, GECOS, HOMEDIR, PASSWORD_EXPIRY_DATE, PROPAGATION, STATUS_ID, STATUS_DATE, PRIMARY_GROUP, AFFILIATION_GROUP FROM PP_USERS;

DROP TABLE PP_USERS;

CREATE TABLE PP_USERS (
  USER_ID INTEGER PRIMARY KEY NOT NULL,
  CRSID varchar2(10) NOT NULL,
  ENGID text,
  UID integer(11),
  GECOS varchar2(100),
  HOMEDIR varchar2(100),
  PASSWORD_EXPIRY_DATE varchar2(100),
  PROPAGATION varchar2(100),
  STATUS_ID integer(11),
  STATUS_DATE date,
  PRIMARY_GROUP integer(11),
  AFFILIATION_GROUP integer(11),
  FOREIGN KEY (PRIMARY_GROUP) REFERENCES PP_GROUPS(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (STATUS_ID) REFERENCES PP_STATUSES(STATUS_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX PP_USERS_idx_PRIMARY_GROUP03 ON PP_USERS (PRIMARY_GROUP);

CREATE INDEX PP_USERS_idx_STATUS_ID03 ON PP_USERS (STATUS_ID);

CREATE UNIQUE INDEX both04 ON PP_USERS (ENGID, CRSID);

INSERT INTO PP_USERS SELECT USER_ID, CRSID, ENGID, UID, GECOS, HOMEDIR, PASSWORD_EXPIRY_DATE, PROPAGATION, STATUS_ID, STATUS_DATE, PRIMARY_GROUP, AFFILIATION_GROUP FROM PP_USERS_temp_alter;

DROP TABLE PP_USERS_temp_alter;


COMMIT;

