-- Convert schema 'db/EngDatabase-Schema-0.18-SQLite.sql' to 'db/EngDatabase-Schema-0.19-SQLite.sql':;

BEGIN;

CREATE UNIQUE INDEX PP_GROUPS_GID02 ON PP_GROUPS (GID);

CREATE UNIQUE INDEX PP_USERS_CRSID02 ON PP_USERS (CRSID);

CREATE UNIQUE INDEX PP_USERS_ENGID02 ON PP_USERS (ENGID);

CREATE UNIQUE INDEX PP_USERS_UID02 ON PP_USERS (UID);

CREATE TEMPORARY TABLE PP_USER_CAPABILITIES_temp_alter (
  CAPABILITIES_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer NOT NULL,
  AD_ENABLED integer,
  AD_PASSWORD integer,
  AUTOMOUNTER integer,
  TRUST_ALLOWED integer,
  UNIX_PASSWD integer,
  UNIX_ENABLED integer,
  PROP_DEPT integer,
  PROP_MAIL integer,
  PROP_DIVA integer,
  PROP_DIVB integer,
  PROP_DIVF integer,
  PROP_FLUID integer,
  PROP_STRUCT integer,
  PROP_WHITTLE integer,
  PROP_WORKS integer,
  PROP_TEST integer,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID)
);

INSERT INTO PP_USER_CAPABILITIES_temp_alter( CAPABILITIES_ID, USER_ID, AD_PASSWORD, AUTOMOUNTER, AD_ENABLED, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_DEPT, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST) SELECT CAPABILITIES_ID, USER_ID, AD_PASSWORD, AUTOMOUNTER, AD_ENABLED, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_DEPT, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_USER_CAPABILITIES;

DROP TABLE PP_USER_CAPABILITIES;

CREATE TABLE PP_USER_CAPABILITIES (
  CAPABILITIES_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer NOT NULL,
  AD_ENABLED integer,
  AD_PASSWORD integer,
  AUTOMOUNTER integer,
  TRUST_ALLOWED integer,
  UNIX_PASSWD integer,
  UNIX_ENABLED integer,
  PROP_DEPT integer,
  PROP_MAIL integer,
  PROP_DIVA integer,
  PROP_DIVB integer,
  PROP_DIVF integer,
  PROP_FLUID integer,
  PROP_STRUCT integer,
  PROP_WHITTLE integer,
  PROP_WORKS integer,
  PROP_TEST integer,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID)
);

CREATE INDEX PP_USER_CAPABILITIES_idx_US00 ON PP_USER_CAPABILITIES (USER_ID);

CREATE UNIQUE INDEX PP_USER_CAPABILITIES_CAPABI00 ON PP_USER_CAPABILITIES (CAPABILITIES_ID, USER_ID);

INSERT INTO PP_USER_CAPABILITIES SELECT CAPABILITIES_ID, USER_ID, AD_ENABLED, AD_PASSWORD, AUTOMOUNTER, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_DEPT, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_USER_CAPABILITIES_temp_alter;

DROP TABLE PP_USER_CAPABILITIES_temp_alter;


COMMIT;

