-- Convert schema 'db/LinWin-Schema-0.15-SQLite.sql' to 'db/LinWin-Schema-0.16-SQLite.sql':;

BEGIN;

CREATE TEMPORARY TABLE PP_GROUPS_temp_alter (
  GROUP_ID INTEGER PRIMARY KEY NOT NULL,
  GID integer NOT NULL,
  GROUP_NAME text,
  GROUP_DESC text
);

INSERT INTO PP_GROUPS_temp_alter( GROUP_ID, GID, GROUP_NAME, GROUP_DESC) SELECT GROUP_ID, GID, GROUP_NAME, GROUP_DESC FROM PP_GROUPS;

DROP TABLE PP_GROUPS;

CREATE TABLE PP_GROUPS (
  GROUP_ID INTEGER PRIMARY KEY NOT NULL,
  GID integer NOT NULL,
  GROUP_NAME text,
  GROUP_DESC text
);

CREATE UNIQUE INDEX PP_GROUPS_GROUP_NAME_GID03 ON PP_GROUPS (GROUP_NAME, GID);

INSERT INTO PP_GROUPS SELECT GROUP_ID, GID, GROUP_NAME, GROUP_DESC FROM PP_GROUPS_temp_alter;

DROP TABLE PP_GROUPS_temp_alter;


COMMIT;

