-- Convert schema 'db/EngDatabase-Schema-0.21-SQLite.sql' to 'db/EngDatabase-Schema-0.22-SQLite.sql':;

BEGIN;

CREATE TEMPORARY TABLE PP_ATTRIBUTES_temp_alter (
  ATTRIBUTE_ID INTEGER PRIMARY KEY NOT NULL,
  ATTRIBUTE_NAME varchar2(100) NOT NULL
);

INSERT INTO PP_ATTRIBUTES_temp_alter( ATTRIBUTE_ID, ATTRIBUTE_NAME) SELECT ATTRIBUTE_ID, ATTRIBUTE_NAME FROM PP_ATTRIBUTES;

DROP TABLE PP_ATTRIBUTES;

CREATE TABLE PP_ATTRIBUTES (
  ATTRIBUTE_ID INTEGER PRIMARY KEY NOT NULL,
  ATTRIBUTE_NAME varchar2(100) NOT NULL
);

CREATE UNIQUE INDEX name03 ON PP_ATTRIBUTES (ATTRIBUTE_NAME);

INSERT INTO PP_ATTRIBUTES SELECT ATTRIBUTE_ID, ATTRIBUTE_NAME FROM PP_ATTRIBUTES_temp_alter;

DROP TABLE PP_ATTRIBUTES_temp_alter;

CREATE TEMPORARY TABLE PP_GROUPS_temp_alter (
  GROUP_ID INTEGER PRIMARY KEY NOT NULL,
  GID integer(11) NOT NULL,
  GROUP_NAME varchar2(50),
  GROUP_DESC varchar2(100)
);

INSERT INTO PP_GROUPS_temp_alter( GROUP_ID, GID, GROUP_NAME, GROUP_DESC) SELECT GROUP_ID, GID, GROUP_NAME, GROUP_DESC FROM PP_GROUPS;

DROP TABLE PP_GROUPS;

CREATE TABLE PP_GROUPS (
  GROUP_ID INTEGER PRIMARY KEY NOT NULL,
  GID integer(11) NOT NULL,
  GROUP_NAME varchar2(50),
  GROUP_DESC varchar2(100)
);

CREATE UNIQUE INDEX GID03 ON PP_GROUPS (GID);

INSERT INTO PP_GROUPS SELECT GROUP_ID, GID, GROUP_NAME, GROUP_DESC FROM PP_GROUPS_temp_alter;

DROP TABLE PP_GROUPS_temp_alter;

CREATE TEMPORARY TABLE PP_GROUP_MEMBERSHIPS_temp_alter (
  GROUP_MEMBERSHIP_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  GROUP_ID integer(11) NOT NULL,
  PRIMARY_GROUP integer(1) NOT NULL,
  AFFILIATION_GROUP integer(1) NOT NULL,
  FOREIGN KEY (GROUP_ID) REFERENCES PP_GROUPS(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PP_GROUP_MEMBERSHIPS_temp_alter( GROUP_MEMBERSHIP_ID, USER_ID, GROUP_ID, PRIMARY_GROUP, AFFILIATION_GROUP) SELECT GROUP_MEMBERSHIP_ID, USER_ID, GROUP_ID, PRIMARY_GROUP, AFFILIATION_GROUP FROM PP_GROUP_MEMBERSHIPS;

DROP TABLE PP_GROUP_MEMBERSHIPS;

CREATE TABLE PP_GROUP_MEMBERSHIPS (
  GROUP_MEMBERSHIP_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  GROUP_ID integer(11) NOT NULL,
  PRIMARY_GROUP integer(1) NOT NULL,
  AFFILIATION_GROUP integer(1) NOT NULL,
  FOREIGN KEY (GROUP_ID) REFERENCES PP_GROUPS(GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX PP_GROUP_MEMBERSHIPS_idx_GR00 ON PP_GROUP_MEMBERSHIPS (GROUP_ID);

CREATE INDEX PP_GROUP_MEMBERSHIPS_idx_US00 ON PP_GROUP_MEMBERSHIPS (USER_ID);

CREATE UNIQUE INDEX affiliationgroup03 ON PP_GROUP_MEMBERSHIPS (USER_ID, AFFILIATION_GROUP);

CREATE UNIQUE INDEX both0203 ON PP_GROUP_MEMBERSHIPS (USER_ID, PRIMARY_GROUP, AFFILIATION_GROUP);

CREATE UNIQUE INDEX primarygroup03 ON PP_GROUP_MEMBERSHIPS (USER_ID, PRIMARY_GROUP);

INSERT INTO PP_GROUP_MEMBERSHIPS SELECT GROUP_MEMBERSHIP_ID, USER_ID, GROUP_ID, PRIMARY_GROUP, AFFILIATION_GROUP FROM PP_GROUP_MEMBERSHIPS_temp_alter;

DROP TABLE PP_GROUP_MEMBERSHIPS_temp_alter;

CREATE TEMPORARY TABLE PP_STATUSES_temp_alter (
  STATUS_ID INTEGER PRIMARY KEY NOT NULL,
  STATUS_NAME varchar2(100),
  AD_PASSWORD integer(1),
  AUTOMOUNTER integer(1),
  AD_ENABLED integer(1),
  TRUST_ALLOWED integer(1),
  UNIX_PASSWD integer(1),
  UNIX_ENABLED integer(1),
  PROP_TEACH integer(1),
  PROP_MAIL integer(1),
  PROP_DIVA integer(1),
  PROP_DIVB integer(1),
  PROP_DIVF integer(1),
  PROP_FLUID integer(1),
  PROP_STRUCT integer(1),
  PROP_WHITTLE integer(1),
  PROP_WORKS integer(1),
  PROP_TEST integer(1)
);

INSERT INTO PP_STATUSES_temp_alter( STATUS_ID, STATUS_NAME, AD_PASSWORD, AUTOMOUNTER, AD_ENABLED, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_TEACH, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST) SELECT STATUS_ID, STATUS_NAME, AD_PASSWORD, AUTOMOUNTER, AD_ENABLED, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_TEACH, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_STATUSES;

DROP TABLE PP_STATUSES;

CREATE TABLE PP_STATUSES (
  STATUS_ID INTEGER PRIMARY KEY NOT NULL,
  STATUS_NAME varchar2(100),
  AD_PASSWORD integer(1),
  AUTOMOUNTER integer(1),
  AD_ENABLED integer(1),
  TRUST_ALLOWED integer(1),
  UNIX_PASSWD integer(1),
  UNIX_ENABLED integer(1),
  PROP_TEACH integer(1),
  PROP_MAIL integer(1),
  PROP_DIVA integer(1),
  PROP_DIVB integer(1),
  PROP_DIVF integer(1),
  PROP_FLUID integer(1),
  PROP_STRUCT integer(1),
  PROP_WHITTLE integer(1),
  PROP_WORKS integer(1),
  PROP_TEST integer(1)
);

CREATE UNIQUE INDEX PP_STATUSES_STATUS_NAME03 ON PP_STATUSES (STATUS_NAME);

INSERT INTO PP_STATUSES SELECT STATUS_ID, STATUS_NAME, AD_PASSWORD, AUTOMOUNTER, AD_ENABLED, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_TEACH, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_STATUSES_temp_alter;

DROP TABLE PP_STATUSES_temp_alter;

CREATE TEMPORARY TABLE PP_USERS_temp_alter (
  USER_ID INTEGER PRIMARY KEY NOT NULL,
  CRSID varchar2(10) NOT NULL,
  ENGID text,
  UID integer(11) NOT NULL,
  GECOS varchar2(100),
  HOMEDIR varchar2(100),
  PASSWORD_EXPIRY_DATE varchar2(100),
  PROPAGATION varchar2(100),
  STATUS_ID integer(11) NOT NULL,
  STATUS_DATE date,
  FOREIGN KEY (STATUS_ID) REFERENCES PP_STATUSES(STATUS_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PP_USERS_temp_alter( USER_ID, CRSID, ENGID, UID, GECOS, HOMEDIR, PASSWORD_EXPIRY_DATE, PROPAGATION, STATUS_ID, STATUS_DATE) SELECT USER_ID, CRSID, ENGID, UID, GECOS, HOMEDIR, PASSWORD_EXPIRY_DATE, PROPAGATION, STATUS_ID, STATUS_DATE FROM PP_USERS;

DROP TABLE PP_USERS;

CREATE TABLE PP_USERS (
  USER_ID INTEGER PRIMARY KEY NOT NULL,
  CRSID varchar2(10) NOT NULL,
  ENGID text,
  UID integer(11) NOT NULL,
  GECOS varchar2(100),
  HOMEDIR varchar2(100),
  PASSWORD_EXPIRY_DATE varchar2(100),
  PROPAGATION varchar2(100),
  STATUS_ID integer(11) NOT NULL,
  STATUS_DATE date,
  FOREIGN KEY (STATUS_ID) REFERENCES PP_STATUSES(STATUS_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX PP_USERS_idx_STATUS_ID03 ON PP_USERS (STATUS_ID);

CREATE UNIQUE INDEX CRSID03 ON PP_USERS (CRSID);

CREATE UNIQUE INDEX ENGID03 ON PP_USERS (ENGID);

CREATE UNIQUE INDEX both05 ON PP_USERS (ENGID, CRSID);

INSERT INTO PP_USERS SELECT USER_ID, CRSID, ENGID, UID, GECOS, HOMEDIR, PASSWORD_EXPIRY_DATE, PROPAGATION, STATUS_ID, STATUS_DATE FROM PP_USERS_temp_alter;

DROP TABLE PP_USERS_temp_alter;

CREATE TEMPORARY TABLE PP_USER_ATTRIBUTES_temp_alter (
  USER_ATTRIBUTE_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  ATTRIBUTE_ID integer(11) NOT NULL,
  ATTRIBUTE_VALUE varchar2(100),
  ATTRIBUTE_EFFECTIVE_DATE date,
  ATTRIBUTE_EXPIRY_DATE date,
  FOREIGN KEY (ATTRIBUTE_ID) REFERENCES PP_ATTRIBUTES(ATTRIBUTE_ID),
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PP_USER_ATTRIBUTES_temp_alter( USER_ATTRIBUTE_ID, USER_ID, ATTRIBUTE_ID, ATTRIBUTE_VALUE, ATTRIBUTE_EFFECTIVE_DATE, ATTRIBUTE_EXPIRY_DATE) SELECT USER_ATTRIBUTE_ID, USER_ID, ATTRIBUTE_ID, ATTRIBUTE_VALUE, ATTRIBUTE_EFFECTIVE_DATE, ATTRIBUTE_EXPIRY_DATE FROM PP_USER_ATTRIBUTES;

DROP TABLE PP_USER_ATTRIBUTES;

CREATE TABLE PP_USER_ATTRIBUTES (
  USER_ATTRIBUTE_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  ATTRIBUTE_ID integer(11) NOT NULL,
  ATTRIBUTE_VALUE varchar2(100),
  ATTRIBUTE_EFFECTIVE_DATE date,
  ATTRIBUTE_EXPIRY_DATE date,
  FOREIGN KEY (ATTRIBUTE_ID) REFERENCES PP_ATTRIBUTES(ATTRIBUTE_ID),
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX PP_USER_ATTRIBUTES_idx_ATTR00 ON PP_USER_ATTRIBUTES (ATTRIBUTE_ID);

CREATE INDEX PP_USER_ATTRIBUTES_idx_USER00 ON PP_USER_ATTRIBUTES (USER_ID);

CREATE UNIQUE INDEX both0303 ON PP_USER_ATTRIBUTES (USER_ID, ATTRIBUTE_EFFECTIVE_DATE, ATTRIBUTE_EXPIRY_DATE);

CREATE UNIQUE INDEX effective03 ON PP_USER_ATTRIBUTES (USER_ID, ATTRIBUTE_EFFECTIVE_DATE);

CREATE UNIQUE INDEX expiry03 ON PP_USER_ATTRIBUTES (USER_ID, ATTRIBUTE_EXPIRY_DATE);

INSERT INTO PP_USER_ATTRIBUTES SELECT USER_ATTRIBUTE_ID, USER_ID, ATTRIBUTE_ID, ATTRIBUTE_VALUE, ATTRIBUTE_EFFECTIVE_DATE, ATTRIBUTE_EXPIRY_DATE FROM PP_USER_ATTRIBUTES_temp_alter;

DROP TABLE PP_USER_ATTRIBUTES_temp_alter;

CREATE TEMPORARY TABLE PP_USER_CAPABILITIES_temp_alter (
  CAPABILITIES_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  AD_ENABLED integer(1),
  AD_PASSWORD integer(1),
  AUTOMOUNTER integer(1),
  TRUST_ALLOWED integer(1),
  UNIX_PASSWD integer(1),
  UNIX_ENABLED integer(1),
  PROP_TEACH integer(1),
  PROP_MAIL integer(1),
  PROP_DIVA integer(1),
  PROP_DIVB integer(1),
  PROP_DIVF integer(1),
  PROP_FLUID integer(1),
  PROP_STRUCT integer(1),
  PROP_WHITTLE integer(1),
  PROP_WORKS integer(1),
  PROP_TEST integer(1),
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO PP_USER_CAPABILITIES_temp_alter( CAPABILITIES_ID, USER_ID, AD_ENABLED, AD_PASSWORD, AUTOMOUNTER, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_TEACH, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST) SELECT CAPABILITIES_ID, USER_ID, AD_ENABLED, AD_PASSWORD, AUTOMOUNTER, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_TEACH, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_USER_CAPABILITIES;

DROP TABLE PP_USER_CAPABILITIES;

CREATE TABLE PP_USER_CAPABILITIES (
  CAPABILITIES_ID INTEGER PRIMARY KEY NOT NULL,
  USER_ID integer(11) NOT NULL,
  AD_ENABLED integer(1),
  AD_PASSWORD integer(1),
  AUTOMOUNTER integer(1),
  TRUST_ALLOWED integer(1),
  UNIX_PASSWD integer(1),
  UNIX_ENABLED integer(1),
  PROP_TEACH integer(1),
  PROP_MAIL integer(1),
  PROP_DIVA integer(1),
  PROP_DIVB integer(1),
  PROP_DIVF integer(1),
  PROP_FLUID integer(1),
  PROP_STRUCT integer(1),
  PROP_WHITTLE integer(1),
  PROP_WORKS integer(1),
  PROP_TEST integer(1),
  FOREIGN KEY (USER_ID) REFERENCES PP_USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX PP_USER_CAPABILITIES_idx_US00 ON PP_USER_CAPABILITIES (USER_ID);

CREATE UNIQUE INDEX PP_USER_CAPABILITIES_CAPABI00 ON PP_USER_CAPABILITIES (CAPABILITIES_ID, USER_ID);

INSERT INTO PP_USER_CAPABILITIES SELECT CAPABILITIES_ID, USER_ID, AD_ENABLED, AD_PASSWORD, AUTOMOUNTER, TRUST_ALLOWED, UNIX_PASSWD, UNIX_ENABLED, PROP_TEACH, PROP_MAIL, PROP_DIVA, PROP_DIVB, PROP_DIVF, PROP_FLUID, PROP_STRUCT, PROP_WHITTLE, PROP_WORKS, PROP_TEST FROM PP_USER_CAPABILITIES_temp_alter;

DROP TABLE PP_USER_CAPABILITIES_temp_alter;


COMMIT;

