-- Convert schema 'db/EngDatabase-Schema-0.20-SQLite.sql' to 'db/EngDatabase-Schema-0.21-SQLite.sql':;

BEGIN;

DROP INDEX PP_GROUPS_GROUP_NAME_GID;

CREATE UNIQUE INDEX affiliationgroup02 ON PP_GROUP_MEMBERSHIPS (USER_ID, AFFILIATION_GROUP);

CREATE UNIQUE INDEX both03 ON PP_GROUP_MEMBERSHIPS (USER_ID, PRIMARY_GROUP, AFFILIATION_GROUP);

CREATE UNIQUE INDEX primarygroup02 ON PP_GROUP_MEMBERSHIPS (USER_ID, PRIMARY_GROUP);

CREATE UNIQUE INDEX both0202 ON PP_USER_ATTRIBUTES (USER_ID, ATTRIBUTE_EFFECTIVE_DATE, ATTRIBUTE_EXPIRY_DATE);

CREATE UNIQUE INDEX effective02 ON PP_USER_ATTRIBUTES (USER_ID, ATTRIBUTE_EFFECTIVE_DATE);

CREATE UNIQUE INDEX expiry02 ON PP_USER_ATTRIBUTES (USER_ID, ATTRIBUTE_EXPIRY_DATE);


COMMIT;

