-- 
-- Created by SQL::Translator::Producer::PostgreSQL
-- Created on Thu Oct 24 17:11:32 2013
-- 
--
-- Table: PP_ATTRIBUTES.
--
DROP TABLE "PP_ATTRIBUTES" CASCADE;
CREATE TABLE "PP_ATTRIBUTES" (
  "ATTRIBUTE_ID" integer NOT NULL,
  "ATTRIBUTE_NAME" text NOT NULL,
  PRIMARY KEY ("ATTRIBUTE_ID"),
  CONSTRAINT "PP_ATTRIBUTES_ATTRIBUTE_NAME" UNIQUE ("ATTRIBUTE_NAME")
);

--
-- Table: PP_GROUPS.
--
DROP TABLE "PP_GROUPS" CASCADE;
CREATE TABLE "PP_GROUPS" (
  "GROUP_ID" integer NOT NULL,
  "GID" integer NOT NULL,
  "GROUP_NAME" text,
  "GROUP_DESC" text,
  PRIMARY KEY ("GROUP_ID"),
  CONSTRAINT "GID" UNIQUE ("GID")
);

--
-- Table: PP_STATUSES.
--
DROP TABLE "PP_STATUSES" CASCADE;
CREATE TABLE "PP_STATUSES" (
  "STATUS_ID" integer NOT NULL,
  "STATUS_NAME" ,
  "AD_PASSWORD" ,
  "AUTOMOUNTER" ,
  "AD_ENABLED" ,
  "TRUST_ALLOWED" ,
  "UNIX_PASSWD" ,
  "UNIX_ENABLED" ,
  "PROP_TEACH" ,
  "PROP_MAIL" ,
  "PROP_DIVA" ,
  "PROP_DIVB" ,
  "PROP_DIVF" ,
  "PROP_FLUID" ,
  "PROP_STRUCT" ,
  "PROP_WHITTLE" ,
  "PROP_WORKS" ,
  "PROP_TEST" ,
  PRIMARY KEY ("STATUS_ID"),
  CONSTRAINT "PP_STATUSES_STATUS_NAME" UNIQUE ("STATUS_NAME")
);

--
-- Table: PP_USERS.
--
DROP TABLE "PP_USERS" CASCADE;
CREATE TABLE "PP_USERS" (
  "USER_ID" integer NOT NULL,
  "CRSID" text NOT NULL,
  "ENGID" text,
  "UID" integer NOT NULL,
  "GECOS" ,
  "HOMEDIR" ,
  "PASSWORD_EXPIRY_DATE" ,
  "PROPAGATION" ,
  "STATUS_ID" integer NOT NULL,
  "STATUS_DATE" ,
  PRIMARY KEY ("USER_ID"),
  CONSTRAINT "PP_USERS_ENGID_CRSID_UID" UNIQUE ("ENGID", "CRSID", "UID")
);
CREATE INDEX "PP_USERS_idx_STATUS_ID" on "PP_USERS" ("STATUS_ID");

--
-- Table: PP_USER_CAPABILITIES.
--
DROP TABLE "PP_USER_CAPABILITIES" CASCADE;
CREATE TABLE "PP_USER_CAPABILITIES" (
  "CAPABILITIES_ID" integer NOT NULL,
  "USER_ID" integer NOT NULL,
  "AD_ENABLED" integer,
  "AD_PASSWORD" integer,
  "AUTOMOUNTER" integer,
  "TRUST_ALLOWED" integer,
  "UNIX_PASSWD" integer,
  "UNIX_ENABLED" integer,
  "PROP_TEACH" integer,
  "PROP_MAIL" integer,
  "PROP_DIVA" integer,
  "PROP_DIVB" integer,
  "PROP_DIVF" integer,
  "PROP_FLUID" integer,
  "PROP_STRUCT" integer,
  "PROP_WHITTLE" integer,
  "PROP_WORKS" integer,
  "PROP_TEST" integer,
  PRIMARY KEY ("CAPABILITIES_ID"),
  CONSTRAINT "PP_USER_CAPABILITIES_CAPABILITIES_ID_USER_ID" UNIQUE ("CAPABILITIES_ID", "USER_ID")
);
CREATE INDEX "PP_USER_CAPABILITIES_idx_USER_ID" on "PP_USER_CAPABILITIES" ("USER_ID");

--
-- Table: PP_GROUP_MEMBERSHIPS.
--
DROP TABLE "PP_GROUP_MEMBERSHIPS" CASCADE;
CREATE TABLE "PP_GROUP_MEMBERSHIPS" (
  "GROUP_MEMBERSHIP_ID" integer NOT NULL,
  "USER_ID" integer NOT NULL,
  "GROUP_ID" integer NOT NULL,
  "PRIMARY_GROUP" integer NOT NULL,
  "AFFILIATION_GROUP" integer NOT NULL,
  PRIMARY KEY ("GROUP_MEMBERSHIP_ID"),
  CONSTRAINT "affiliationgroup" UNIQUE ("USER_ID", "AFFILIATION_GROUP"),
  CONSTRAINT "both" UNIQUE ("USER_ID", "PRIMARY_GROUP", "AFFILIATION_GROUP"),
  CONSTRAINT "primarygroup" UNIQUE ("USER_ID", "PRIMARY_GROUP")
);
CREATE INDEX "PP_GROUP_MEMBERSHIPS_idx_GROUP_ID" on "PP_GROUP_MEMBERSHIPS" ("GROUP_ID");
CREATE INDEX "PP_GROUP_MEMBERSHIPS_idx_USER_ID" on "PP_GROUP_MEMBERSHIPS" ("USER_ID");

--
-- Table: PP_USER_ATTRIBUTES.
--
DROP TABLE "PP_USER_ATTRIBUTES" CASCADE;
CREATE TABLE "PP_USER_ATTRIBUTES" (
  "USER_ATTRIBUTE_ID" integer NOT NULL,
  "USER_ID" text NOT NULL,
  "ATTRIBUTE_ID" integer NOT NULL,
  "ATTRIBUTE_VALUE" ,
  "ATTRIBUTE_EFFECTIVE_DATE" ,
  "ATTRIBUTE_EXPIRY_DATE" ,
  PRIMARY KEY ("USER_ATTRIBUTE_ID"),
  CONSTRAINT "both" UNIQUE ("USER_ID", "ATTRIBUTE_EFFECTIVE_DATE", "ATTRIBUTE_EXPIRY_DATE"),
  CONSTRAINT "effective" UNIQUE ("USER_ID", "ATTRIBUTE_EFFECTIVE_DATE"),
  CONSTRAINT "expiry" UNIQUE ("USER_ID", "ATTRIBUTE_EXPIRY_DATE")
);
CREATE INDEX "PP_USER_ATTRIBUTES_idx_ATTRIBUTE_ID" on "PP_USER_ATTRIBUTES" ("ATTRIBUTE_ID");
CREATE INDEX "PP_USER_ATTRIBUTES_idx_USER_ID" on "PP_USER_ATTRIBUTES" ("USER_ID");

--
-- Foreign Key Definitions
--

ALTER TABLE "PP_USERS" ADD CONSTRAINT "PP_USERS_fk_STATUS_ID" FOREIGN KEY ("STATUS_ID")
  REFERENCES "PP_STATUSES" ("STATUS_ID") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;

ALTER TABLE "PP_USER_CAPABILITIES" ADD CONSTRAINT "PP_USER_CAPABILITIES_fk_USER_ID" FOREIGN KEY ("USER_ID")
  REFERENCES "PP_USERS" ("USER_ID") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;

ALTER TABLE "PP_GROUP_MEMBERSHIPS" ADD CONSTRAINT "PP_GROUP_MEMBERSHIPS_fk_GROUP_ID" FOREIGN KEY ("GROUP_ID")
  REFERENCES "PP_GROUPS" ("GROUP_ID") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;

ALTER TABLE "PP_GROUP_MEMBERSHIPS" ADD CONSTRAINT "PP_GROUP_MEMBERSHIPS_fk_USER_ID" FOREIGN KEY ("USER_ID")
  REFERENCES "PP_USERS" ("USER_ID") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;

ALTER TABLE "PP_USER_ATTRIBUTES" ADD CONSTRAINT "PP_USER_ATTRIBUTES_fk_ATTRIBUTE_ID" FOREIGN KEY ("ATTRIBUTE_ID")
  REFERENCES "PP_ATTRIBUTES" ("ATTRIBUTE_ID") DEFERRABLE;

ALTER TABLE "PP_USER_ATTRIBUTES" ADD CONSTRAINT "PP_USER_ATTRIBUTES_fk_USER_ID" FOREIGN KEY ("USER_ID")
  REFERENCES "PP_USERS" ("USER_ID") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE;

